# This is a basic workflow to test the OpenZiti Edge Client 

name: Openziti edge client action

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  download-edge-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download the edge client
        run: wget -q "https://github.com/openziti/ziti-tunnel-sdk-c/releases/latest/download/ziti-edge-tunnel-Linux_$(uname -p).zip" && unzip ./ziti-edge-tunnel-Linux_$(uname -p).zip && rm ./ziti-edge-tunnel-Linux_$(uname -p).zip && chmod -c +x ./ziti-edge-tunnel && ./ziti-edge-tunnel version

      - name: Test the ziti-edge-client
        run: ./ziti-edge-tunnel version
        
      - name: Create Identity
        env:
          ID_SECRET: ${{ secrets.STRONGID }}

        run: echo $ID_SECRET >> myidentity.json
        
      - name: Validate Identity
        run: cat myidentity.json
       
      - name: Add Identity
        run: ./ziti-edge-tunnel add myidentity.json
        
      - name: Execute the Edge client
        run: sudo nohup ./ziti-edge-tunnel run --identity-dir ./ > log.txt &
        
      - name: Check Tunnel Status
        run: sudo nohup ./ziti-edge-tunnel tunnel_status
          
      - name: Test a service connection
        run: ping darkside.api.com
        
      - name: Test a service connection
        run: wget http://darkside.api.com/api/people/1
